### ISSUE TITLE
[V3] Preparation status

### ISSUE THREAD

**Issue by ErikSchierboom** [ErikSchierboom/fsharp#16]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism V3, we've created a checklist:

- [ ] [Configure online editor](#9)
- [ ] [Add key features](#10)
- [ ] [Add tags](#11)
- [ ] [Add prerequisites to Practice Exercises](#12)
- [ ] [Pass linting checks](#13)
- [ ] [Build Test Runner](#14)
- [ ] [Build Analyzer and Representer](#15) (optional)

We (the Exercism Team) will check off the above items. Track maintainers should only use this list as a status report.

## Tracking

https://github.com/exercism/v3-launch/issues/7
