### ISSUE TITLE
[V3] Preparation status

### ISSUE THREAD

**Issue by ErikSchierboom** [ErikSchierboom/fsharp#24]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism V3, we've created a checklist:

- [ ] [Configure online editor](https://github.com/ErikSchierboom/fsharp/issues/17)
- [ ] [Add key features](https://github.com/ErikSchierboom/fsharp/issues/18)
- [ ] [Add tags](https://github.com/ErikSchierboom/fsharp/issues/19)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/ErikSchierboom/fsharp/issues/20)
- [ ] [Pass linting checks](https://github.com/ErikSchierboom/fsharp/issues/21)
- [ ] [Build Test Runner](https://github.com/ErikSchierboom/fsharp/issues/22)
- [ ] [Build Analyzer and Representer](https://github.com/ErikSchierboom/fsharp/issues/23) (optional)

We (the Exercism Team) will check off the above items. Track maintainers should only use this list as a status report.

## Tracking

https://github.com/exercism/v3-launch/issues/7
