### ISSUE TITLE
[V3] Preparation status

### ISSUE THREAD

**Issue by ErikSchierboom** [ErikSchierboom/fsharp#40]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism V3, the following needs to be done:

- [ ] [Configure online editor](https://github.com/ErikSchierboom/fsharp/issues/25)
- [ ] [Add key features](https://github.com/ErikSchierboom/fsharp/issues/26)
- [ ] [Add tags](https://github.com/ErikSchierboom/fsharp/issues/27)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/ErikSchierboom/fsharp/issues/28)
- [ ] [Pass linting checks](https://github.com/ErikSchierboom/fsharp/issues/29)
- [ ] [Build Test Runner](https://github.com/ErikSchierboom/fsharp/issues/30)
- [ ] [Build Analyzer and Representer](https://github.com/ErikSchierboom/fsharp/issues/31) (optional)

We (the Exercism Team) will check off the above items. Track maintainers should only use this list as a status report.

## Tracking

https://github.com/exercism/v3-launch/issues/7
