### ISSUE TITLE
[v3] Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [ErikSchierboom/fsharp#49]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [ ] [Configure online editor](https://github.com/ErikSchierboom/fsharp/issues/41)
- [ ] [Add key features](https://github.com/ErikSchierboom/fsharp/issues/42)
- [ ] [Add tags](https://github.com/ErikSchierboom/fsharp/issues/43)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/ErikSchierboom/fsharp/issues/44)
- [ ] [Pass linting checks](https://github.com/ErikSchierboom/fsharp/issues/45)
- [ ] [Build Test Runner](https://github.com/ErikSchierboom/fsharp/issues/46)
- [ ] [Build Analyzer and Representer](https://github.com/ErikSchierboom/fsharp/issues/47) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
